name: vitest
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/pnpm
          key: ${{ runner.os }}-todo-${{ hashFiles(format('{0}{1}', github.workspace, '/pnpm-lock.yaml')) }}
          restore-keys: ${{ runner.os }}-todo-
      - name: Install node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install
      - name: test
        run: TZ=Asia/Tokyo pnpm test
